### ISSUE TITLE
html assets not generated with report

### ISSUE THREAD

**Issue by thisjustin816** [microsoft/ApplicationInspector#257] opened 2020-08-04 15:56 UTC
**Describe the bug**
The HTML report doesn't display correctly because the html folder is missing.

**To Reproduce**
1. `dotnet tool install --global Microsoft.CST.ApplicationInspector.CLI --add-source https://api.nuget.org/v3/index.json --ignore-failed-sources`
2. `appinspector analyze -s .`

**Expected behavior**
App inspector runs and opens the html report, displaying with all needed assets.

**Screenshots**
![image](https://user-images.githubusercontent.com/41129295/89315910-3f7aad00-d630-11ea-8172-cc78d0bf2a03.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 2004
 - Browser: New Edge
 - Version: ApplicationInspector.CLI 1.2.47+d18ddea15c

**Comment by thisjustin816** [comment] 2020-08-04 17:22
Possibly a duplicate of #93

**Comment by guyacosta** [comment] 2020-08-05 14:53
Duplicate of open issue being worked on #241

**Closed by guyacosta** 2020-08-05 14:53 UTC
