### ISSUE TITLE
Icons don't display in output report

### ISSUE THREAD

**Issue by rpratik786** [microsoft/ApplicationInspector#240] opened 2020-07-02 11:06 UTC
In the features tab, the high gauge, low gauge, and medium gauge images don't show up. This is due to discrepancy in the case of images in the html/resources/images folder and the actual output.html file.
Attaching images for your reference
![real-file-name-in-small-caps](https://user-images.githubusercontent.com/31565959/86351554-14dcb380-bc82-11ea-8260-c73a00660da5.png)
![mentioned-file-name-in-camel-case](https://user-images.githubusercontent.com/31565959/86351559-160de080-bc82-11ea-813f-ed16aec59ec2.png)

**Comment by guyacosta** [comment] 2020-07-05 20:44
@rpratik786 having difficulty reproducing the issue.  Have just downloaded new using both the Releases 1.2.34 package for Windows as well as the code base as a build and both fail to exhibit the problem.  The path in the html is relative and should always work unless you attempt to relocate the output report file elsewhere than the default.  Note when supplying output argument -o the system puts a console message out that it is ignored for the default or html format to ensure this path will work for icons etc.  There is a future requirement to overcome this current limitation that will be addressed but we don't support taking the output file and moving elsewhere so fyi.  Since I can see the path appears ok in the browser but can't reproduce the issue, would you reattempt from scratch and steps used.  Thanks!

**Comment by gfs** [comment] 2020-07-06 13:54
@guyacosta I think it would be more intuitive to users if the output were a self contained folder that the user can relocate. Should we turn this into a feature request for that?

**Comment by guyacosta** [comment] 2020-07-06 14:57
@gfs Yeah is a step closer and low hanging enough to turn around quickly.  Going to close this issue and open another as a feature since I can't reproduce and the new feature should resolve if there is an issue with it.

**Closed by guyacosta** 2020-07-06 14:57 UTC
