### ISSUE TITLE
Webpack HTML dependency files

### ISSUE THREAD

**Issue by guyacosta** [microsoft/ApplicationInspector#273] opened 2020-08-17 21:48 UTC
Suggestion provided by @gfs 

Description: how to consolidate various js and cs files needed for HTML format report to package them into a reduced set of references and avoid real-time internet reference and download time

My recommendation is as follows. This eliminates all dependency on external files being present on the disc, everything will be in the binary.

- Use [webpack ](https://www.c-sharpcorner.com/article/getting-started-with-webpack/)either pre-build or as part of the pre-build build tasks to compile all your js and css assets. It sounds like your html is also one file too, which is great.
- Embed those into your binary. Set the build task to EmbeddedResource in visual studio.
- Have a simple test to ensure that the embeds are there.
- At runtime access the embedded files like you do for your rules.
- Do whatever processing you need to.
- Write the embedded files to disc where the user has selected.

**Comment by gfs** [comment] 2020-08-17 22:08
Looks good guy. Let me know if you need any help.

**Comment by rback123** [comment] 2020-09-01 20:46
Thanks for digging into this one. I hope this resolves the issue I'm running into. I'm running v1.2.58 and the HTML output is non-functional and the output looks like #264. I tried from macOS and from Ubuntu and couldn't get either to produce usable output from the CLI.

I noticed a few resources are no longer referenced in my `output.html` when compared to an old report sample I saw online. I'm not sure this information is helpful or related but the first item looks highly important. The other JavaScript resources (query, ace, d3, c3, popper) are now sourced from `cdnjs.cloudflare.com` but I no longer see these: 
1. `appinspector.js`
2. `ext-settings_menu.js`
3. `ext-modelist.js`
4. `ext-beautify.js`

**Comment by ggjacosta** [comment] 2020-09-02 01:30
I will verify this and get back to you tonight.  Shouldn't see it in the 1.2.58 version. There are fewer resources reference because they are embedded in the HTML

**Comment by gfs** [comment] 2020-09-02 01:46
I can't reproduce this using the dotnet tool version.

You can install that version (if you have the .NET SDK installed) with `dotnet tool install -g Microsoft.CST.ApplicationInspector.CLI`

```
PS D:\GitHub> appinspector analyze -s .\LogicalAnalyzer\
The output file does not have an html or htm extension and may not open properly in your browser
Analyze command running
100% source files processed
The output.html file size is large and may render slowly.  Consider running using alternate output format options as needed.
Opening default browser to output.html report
Analyze command completed
Additional details may be found in log file at C:\Users\Gstoc\.dotnet\tools\.store\microsoft.cst.applicationinspector.cli\1.2.58\microsoft.cst.applicationinspector.cli\1.2.58\tools\netcoreapp3.1\any\appinspector.log.txt
```

![image](https://user-images.githubusercontent.com/98900/91922680-5b02c300-ec83-11ea-8752-0a91dc13bf16.png)

**Comment by rback123** [comment] 2020-09-02 14:01
Thanks for looking into this. I still have the error and will provide more details in a separate issue (See #279) to not detract from this issue.

**Comment by gfs** [comment] 2021-05-26 17:32
Closing in favor of rewriting UI in Blazor.

**Closed by gfs** 2021-05-26 17:32 UTC
Labels: enhancement
