### ISSUE TITLE
Project information not being loaded from CSProj

### ISSUE THREAD

**Issue by gfs** [microsoft/ApplicationInspector#267] opened 2020-08-13 20:08 UTC
### Problem
Project information isn't being loaded into the App Inspector report.

### Steps
1. Get some reproducible code.  For example, OAT.
2. `appinspector analyze -s OAT`

### Result
Report doesn't pick up project information.

![image](https://user-images.githubusercontent.com/98900/90181984-1cee3f80-dd66-11ea-8c75-4e562575500f.png)

**Comment by guyacosta** [comment] 2020-08-14 00:26
I addressed some missing info for VSProject file types.  I couldn't reproduce the missing Analyzed date and Folder values but will watch for it.  Image of result for OAT project using updated PR that should be available later today ![AppInspForOAT](https://user-images.githubusercontent.com/47648296/90199502-34432200-dd92-11ea-853c-c717d7159984.png)

**Comment by guyacosta** [comment] 2020-08-14 00:49
Fixed in #270

**Closed by guyacosta** 2020-08-14 00:49 UTC
Labels: bug
