### ISSUE TITLE
Steps to integrate with Azure Build Pipelines

### ISSUE THREAD

**Issue by joshipalak04** [microsoft/ApplicationInspector#141] opened 2020-02-18 20:41 UTC
It would be great if you could suggest some steps on how do we run this as part of DevOps Pipeline on Azure DevOps.

**Comment by gfs** [comment] 2020-02-26 07:27
@daalcant I propose we use #144 for this.

**Comment by gfs** [comment] 2020-02-26 07:35
Actually this is a dupe of #76.

**Comment by daalcant** [comment] 2020-03-02 09:32
Dupe of #76, closing.

**Closed by daalcant** 2020-03-02 09:32 UTC
